all:
  children:
    nodes:
      hosts:
        node-1:
          ansible_host: localhost
          ansible_port: 2223
          node_id: 1
        node-2:
          ansible_host: localhost
          ansible_port: 2224
          node_id: 2
        node-3:
          ansible_host: localhost
          ansible_port: 2225
          node_id: 3